version: "3"

# Basic usage:
#     $ docker-compose up
#
# Dev environment (code directory mapped into container):
#     $ docker-compose -f docker-compose.yml -f docker-compose-dev.yml up
#
# Full image (all CLI tools installed):
#     $ docker-compose -f docker-compose.yml -f docker-compose-full.yml up
#
# Spiderfoot data resides in a Docker volume
#
#     $ ls -lh /var/lib/docker/volumes/spiderfoot_spiderfoot-data/_data
#       total 104K
#       drwxr-xr-x 2 user user 4.0K Sep 22 09:51 cache
#       -rw-r--r-- 1 user user 100K Sep 22 15:19 spiderfoot.db

services:
  spiderfoot:
    image: ghcr.io/poppopjmp/spiderfoot
    volumes:
      - spiderfoot-data:/var/lib/spiderfoot
      - ./new_directory:/var/lib/spiderfoot/new_directory
    container_name: spiderfoot
    ports:
      - "5001:5001"
      - "5002:5002"
      - "8000:8000"
    restart: unless-stopped
    command: ["python3", "sf.py", "--rest-api"]

  react-web-interface:
    build:
      context: ./react-web-interface
      dockerfile: Dockerfile
    container_name: react-web-interface
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://spiderfoot:8000
    depends_on:
      - spiderfoot

volumes:
  spiderfoot-data:
