name: Docker Image CI
on:
  push:
    branches: [master,"dev*"]
  pull_request:
    branches: [master,"dev*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error
        
    - name: Login to GitHub Container Registry (if needed)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${ github.repository }:v5.2.9
    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
        ignore-unfixed: 'true'
      
    - name: Run container tests
      run: |
        set -e
        IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
        CONTAINER=spiderfoot-test

        # CLI tests
        docker run --rm $IMAGE sf.py -h || { echo 'sf.py -h failed'; exit 1; }
        docker run --rm $IMAGE sf.py --version || { echo 'sf.py --version failed'; exit 1; }
